<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>합격 여부 확인</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
            margin: 0;
            padding: 20px;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            height: 100vh;
        }
        .container {
            background-color: white;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
        }
        input {
            width: 100%;
            padding: 10px;
            margin: 10px 0;
            border: 1px solid #ccc;
            border-radius: 5px;
        }
        button {
            padding: 10px 20px;
            background-color: #28a745;
            color: white;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            font-size: 16px;
        }
        button:hover {
            background-color: #218838;
        }
        .result-container {
            display: none;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            background-color: white;
            padding: 40px;
            border-radius: 20px;
            box-shadow: 0 4px 15px rgba(0, 0, 0, 0.2);
        }
        .result-container h1 {
            color: green;
            font-size: 72px;
            margin: 0;
        }
        .result-container p {
            color: black;
            font-size: 24px;
            margin-top: 20px;
        }
        .logo {
            text-align: center;
            margin-bottom: 20px;
        }
        .logo img {
            max-width: 100%;
            height: auto;
            max-height: 200px; /* 로고의 최대 높이 설정 */
        }
    </style>
</head>
<body>

<div class="container" id="formContainer">
    <div class="logo">
        <img src="university.jpg" alt="대학교 로고" style="max-width: 1000px; height: auto;">
    </div>
    <h2>2025학년도 정시 1차 합격자 발표</h2>
    <h4>- 성명, 수험번호, 생년 월일을 입력하세요.</h4>
    <h5>ㅤ</h5>
    <form id="passForm">
        <label for="name">성명:</label>
        <input type="text" id="name" placeholder="성명을 입력하세요" required>
        <label for="examNumber">수험번호:</label>
        <input type="text" id="examNumber" placeholder="수험번호를 입력하세요" required>
        <label for="dob">생년월일:</label>
        <input type="text" id="dob" placeholder="생년월일을 입력하세요">
        <button type="submit">확인</button>
    </form>
</div>

<div class="result-container" id="resultContainer">
    <div class="logo">
        <img src="university.jpg" alt="대학교 로고" style="max-width: 1000px; height: auto;">
    </div>
    <h5>ㅤ</h5>
    <h5>ㅤ</h5>
    <h1>합격</h1>
    <p>00대학교의 입학을 진심으로 축하드립니다</p>
    <h5>ㅤ</h5>
    <h5>ㅤ</h5>
</div>

<script>
    document.getElementById('passForm').addEventListener('submit', function(event) {
        event.preventDefault(); // 페이지 새로고침 방지

        // 폼 컨테이너 숨기기
        document.getElementById('formContainer').style.display = 'none';

        // 결과 컨테이너 보이기
        document.getElementById('resultContainer').style.display = 'flex';
    });
</script>

</body>
</html>
